image: docker:latest


#before_script:
#  - apk add --no-cache git
#  - git fetch origin
#  - git reset --hard origin/$CI_COMMIT_REF_NAME

services:
 - name: docker:dind
   alias: docker

stages:
    - build
    - deploy

variables:
    DOCKER_REGISTRY: docker.io
    DOCKER_IMAGE: devinit-back
    DOCKER_TLS_CERTDIR: ""

build_job:
    stage: build
    tags:
        - build
    #image: gradle:8.3-jdk17
    before_script:
        - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        - cat "$ENV_FILE" > src/main/resources/.env
    script:
        - echo "빌드를 시작합니다..."
        - docker build -t $DOCKER_HUB_USERNAME/$DOCKER_IMAGE:latest .
        - echo "도커허브에 푸시를 시작합니다..."
        - docker push $DOCKER_HUB_USERNAME/$DOCKER_IMAGE
    after_script:
        - docker logout

deploy_job:
    stage: deploy
    tags:
       - deploy
    before_script:
       - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
      # 환경 변수로 .env 파일 생
    script:
       - echo "Deploying the project..."
       - docker stop devinit-back || true && docker rm devinit-back || true
       - docker pull $DOCKER_HUB_USERNAME/$DOCKER_IMAGE:latest
       - docker run -d --name devinit-back -p 8081:8080 $DOCKER_HUB_USERNAME/$DOCKER_IMAGE:latest
    after_script:
       - docker logout
    when: on_success

