image: docker:latest

services:
 - name: docker:dind
   alias: docker

stages:
    - build
    - deploy

variables:
    DOCKER_REGISTRY: docker.io
    DOCKER_IMAGE: devinit-back
    DOCKER_TLS_CERTDIR: ""

build_job:
    stage: build
    tags:
        - build
    before_script:
        - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        - cat "$ENV_FILE" > src/main/resources/.env
    script:
        - echo "빌드를 시작합니다...."
        - docker build -t $DOCKER_HUB_USERNAME/$DOCKER_IMAGE:latest .
        - echo "도커허브에 푸시를 시작합니다..."
        - docker push $DOCKER_HUB_USERNAME/$DOCKER_IMAGE
    after_script:
        - docker logout
    only:
        - dev

deploy_job:
    stage: deploy
    tags:
       - deploy
    before_script:
       - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    script:
       - echo "Deploying the project..."
       - docker stop devinit-back || true && docker rm devinit-back || true
       - docker pull $DOCKER_HUB_USERNAME/$DOCKER_IMAGE:latest
       - docker run -d --name devinit-back -p 8080:8080 $DOCKER_HUB_USERNAME/$DOCKER_IMAGE:latest
    after_script:
       - docker logout
    when: on_success
    only:
       - dev