image: docker:latest

stages:
    - build
    - deploy
variables:
    DOCKER_REGISTRY: docker.io
    DOCKER_IMAGE: $DOCKER_HUB_USERNAME/devinit-back
    DEV_SEVICE_URL: 34.64.44.54
services:
    - docker:dind

build_job:
    stage: build
    tags:
        - build
    script:
        - echo "Build the project.."
        - echo "현재 브랜치 $CI_COMMIT_REF_NAME"
        - git clone --branch dev https://gitlab-ci-token:$CI_JOB_TOKEN@kdt-gitlab.elice.io/pttrack/class_01/web_project_i/team03/devinit-back.git

        - cd devinit-back
        - chmod +x ./gradlew
        - ./gradlew clean build
    artifacts:
        name: ${CI_COMMIT_SHA}
        expire_in: 1 day
        paths:
            - devint-back/build/libs/*SNAPSHOT.jar
deploy_job:
    stage: deploy
    tags:
        - deploy
    script:
        - echo "Deploying the project.."
