stages:
    - build
    - deploy
variables:
    DOCKER_REGISTRY: docker.io
    DOCKER_IMAGE: $DOCKER_HUB_USERNAME/devinit-back
    DEV_SEVICE_URL: 34.64.44.54
services:
    - docker:dind
before_script:
    - echo "DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
build_job:
    stage: build
    tags:
        - build
    image: docker:latest
    script:
        - echo "Build the project.."

deploy_job:
    stage: deploy
    tags:
        - deploy
    script:
        - echo "Deploying the project.."
