image: docker:latest


#before_script:
#  - apk add --no-cache git
#  - git fetch origin
#  - git reset --hard origin/$CI_COMMIT_REF_NAME

services:
 - name: docker:dind
   alias: docker

stages:
    - build
    - deploy

variables:
    DOCKER_REGISTRY: docker.io
    DOCKER_IMAGE: devinit-back
    DOCKER_TLS_CERTDIR: ""
    JWT_SECRET: $JWT_SECRET
    NAVER_CLIENT_ID: $NAVER_CLIENT_ID
    NAVER_CLIENT_SECRET: $NAVER_CLIENT_SECRET
    GITHUB_CLIENT_ID: $GITHUB_CLIENT_ID
    GITHUB_CLIENT_SECRET: $GITHUB_CLIENT_SECRET
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_REGION: $AWS_REGION
    S3_BUCKET: $S3_BUCKET
    SPRING_PROFILES_ACTIVE: $SPRING_PROFILES_ACTIVE
    DB_URL_LOCAL: $DB_URL_LOCAL
    DB_USERNAME_LOCAL: $DB_USERNAME_LOCAL
    DB_PASSWORD_LOCAL: $DB_PASSWORD_LOCAL
    BASE_URL: $BASE_URL

build_job:
    stage: build
    tags:
        - build
    #image: gradle:8.3-jdk17
    before_script:
        - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        - echo "$DB_URL_LOCAL"
        - echo "$BASE_URL"
        - echo "$SPRING_PROFILES_ACTIVE"
    script:
        - echo "빌드를 시작합니다..."
        #- git clone --branch feature/24-cicd https://gitlab-ci-token:$CI_JOB_TOKEN@kdt-gitlab.elice.io/pttrack/class_01/web_project_i/team03/devinit-back.git
        #- cd devinit-back
        - docker build -t $DOCKER_HUB_USERNAME/$DOCKER_IMAGE:latest .
        - echo "도커허브에 푸시를 시작합니다..."
        - docker push $DOCKER_HUB_USERNAME/$DOCKER_IMAGE
    after_script:
        - docker logout

deploy_job:
    stage: deploy
    tags:
       - deploy
    before_script:
       - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    script:
       - echo "Deploying the project...."
       - docker stop devinit-back || true && docker rm devinit-back || true
       - docker pull $DOCKER_HUB_USERNAME/$DOCKER_IMAGE:latest
       - docker run -d --name devinit-back -p 8081:8080 $DOCKER_HUB_USERNAME/$DOCKER_IMAGE:latest
    after_script:
       - docker logout
    when: on_success
    environment:
       name: dev

