stages:
    - build
    - deploy

build_job:
    stage: build
    tags:
        - build
    script:
        - echo "Build the project.."

deploy_job:
    stage: deploy
    tags:
        - deploy
    script:
        - echo "Deploying the project.."
