stages:
    - build
    - deploy

variables:
    DOCKER_IMAGE: $DOCKER_HUB_USERNAME/devinit

build_job:
    stage: build
    script:
        - echo "Build the project..."

deploy_job:
    stage: deploy
    script:
        - echo "Deploying the project..."
