spring:
  application:
    name: devinit-back
  redirect:
    url: ${BASE_URL}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${BASE_URL}:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${BASE_URL}:8080/login/oauth2/code/github
            authorization-grant-type: authorization_code
            scope: read:user,user:email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    enabled: true

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${S3_BUCKET}
    default-profile-image: https://elice-devinit.s3.ap-northeast-2.amazonaws.com/default_profile_image.png

logging:
  level:
    root: INFO